# Generated by Django 4.1.5 on 2023-01-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Телефон'),
        ),
    ]
