# Generated by Django 4.1.5 on 2023-02-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_advuser_dateborn_alter_advuser_midl_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='job',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Должность'),
        ),
    ]
