# Generated by Django 4.1.5 on 2023-02-11 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_advuser_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300, unique=True, verbose_name='Название')),
                ('date', models.CharField(blank=True, default='', max_length=300, verbose_name='Дата добавления')),
                ('extension', models.CharField(blank=True, default='', max_length=300, verbose_name='Расширение')),
                ('status', models.BooleanField(default=False, verbose_name='Публичный')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
