# Generated by Django 4.1.5 on 2023-02-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_docsfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsfile',
            name='comments',
            field=models.TextField(default='', verbose_name='Комментарий'),
        ),
    ]
