# Generated by Django 4.1.5 on 2023-02-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_docsfile_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsfile',
            name='docs',
            field=models.FileField(blank=True, default='', upload_to='media/docs', verbose_name='Документ'),
        ),
    ]
