# Generated by Django 4.1.5 on 2023-02-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_docsfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsfile',
            name='date',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='docsfile',
            name='name',
            field=models.CharField(default='', max_length=300, unique=True, verbose_name='Название'),
        ),
    ]
