# Generated by Django 4.1.5 on 2023-03-16 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_docsfile_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsfile',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='docsfile',
            name='docs',
            field=models.FileField(default='', upload_to='docs', verbose_name='Документ'),
        ),
        migrations.CreateModel(
            name='SendedDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toUser', models.IntegerField(default=0)),
                ('docsId', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.docsfile', to_field='name', verbose_name='Документ')),
                ('fromUser', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='От пользователя')),
            ],
        ),
    ]
