# Generated by Django 4.1.5 on 2023-03-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_docsfile_comments_alter_docsfile_docs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendeddocs',
            old_name='docsId',
            new_name='docs',
        ),
    ]
