# Generated by Django 4.1.5 on 2023-03-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_sendeddocs_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendeddocs',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
    ]
