# Generated by Django 4.1.5 on 2023-03-30 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_sendeddocs_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendeddocs',
            name='read',
        ),
    ]
